In [1]:
import pandas as pd
from sqlalchemy import create_engine

### Store CSV into DataFrame

In [2]:
csv_file = "../Resource/incidence_rate.csv"
depression_data_df = pd.read_csv(csv_file)
depression_data_df.head()

  location_name sex_name  age_name         cause_name         val
0       Alabama     Male  30 to 34   Eating disorders  314.156047
1       Alabama   Female  70 to 74  Anxiety disorders  330.402128
2       Alabama     Male  75 to 79  Anxiety disorders  332.234053
3       Alabama   Female  75 to 79  Anxiety disorders  274.168163
4       Alabama     Male   80 plus  Anxiety disorders  221.386348

Extract Depressive Disorder and Major depressive disorder from DataFrame

In [6]:
mdd = depression_data_df.loc[depression_data_df['cause_name'].isin(['Major depressive disorder', 'Depressive disorders'])]
mdd

,location_name,sex_name,age_name,cause_name,val
90,Alabama,Female,70 to 74,Major depressive disorder,3079.961332
91,Alabama,Male,75 to 79,Major depressive disorder,1852.236387
92,Alabama,Female,75 to 79,Major depressive disorder,2314.337276
93,Alabama,Male,80 plus,Major depressive disorder,2407.975834
94,Alabama,Female,80 plus,Major depressive disorder,2964.984830
95,Alabama,Male,80 to 84,Major depressive disorder,2044.125596
96,Alabama,Female,80 to 84,Major depressive disorder,2350.184500
98,Alabama,Male,70 to 74,Major depressive disorder,2101.851106
109,Alabama,Female,65 to 69,Major depressive disorder,3836.624164
110,Alabama,Male,65 to 69,Major depressive disorder,2350.314574
111,Alabama,Female,60 to 64,Major depressive disorder,4584.220101
112,Alabama,Male,15 to 19,Major depressive disorder,4346.465338
113,Alabama,Female,15 to 19,Major depressive disorder,9163.517870
114,Alabama,Male,20 to 24,Major depressive disorder,5060.001694
115,Alabama,Female,20 to 24,Major depressive disorder,7966.054855
116,Alabama,Male,25 to 29,Major depressive disorder,4427.391071
117,Alabama,Female,25 to 29,Major depressive disorder,7201.978390
118,Alabama,Male,30 to 34,Major depressive disorder,4324.753104
119,Alabama,Female,30 to 34,Major depressive disorder,7283.972392
120,Alabama,Male,35 to 39,Major depressive disorder,4746.989175
121,Alabama,Female,35 to 39,Major depressive disorder,8196.024453
122,Alabama,Male,40 to 44,Major depressive disorder,4676.230325
123,Alabama,Female,40 to 44,Major depressive disorder,8179.952916
124,Alabama,Male,45 to 49,Major depressive disorder,4122.702956
125,Alabama,Female,45 to 49,Major depressive disorder,7273.361132
126,Alabama,Male,50 to 54,Major depressive disorder,3565.261406
127,Alabama,Female,50 to 54,Major depressive disorder,6356.005048
128,Alabama,Male,55 to 59,Major depressive disorder,3002.983162
129,Alabama,Female,55 to 59,Major depressive disorder,5424.891721
130,Alabama,Male,60 to 64,Major depressive disorder,2597.490791
...,...,...,...,...,...
32019,Wyoming,Female,15 to 19,Major depressive disorder,11231.988783
32020,Wyoming,Female,35 to 39,Major depressive disorder,9430.628960
32021,Wyoming,Female,40 to 44,Major depressive disorder,9380.208925
32022,Wyoming,Male,45 to 49,Major depressive disorder,4671.060947
32023,Wyoming,Female,45 to 49,Major depressive disorder,8302.570032
32024,Wyoming,Male,50 to 54,Major depressive disorder,3951.574403
32025,Wyoming,Female,50 to 54,Major depressive disorder,7209.648992
32026,Wyoming,Male,55 to 59,Major depressive disorder,3223.990126
32027,Wyoming,Female,55 to 59,Major depressive disorder,6097.147965
32028,Wyoming,Male,40 to 44,Major depressive disorder,5383.869000
32029,Wyoming,Male,40 to 44,Depressive disorders,5663.200252
32030,Wyoming,Male,15 to 19,Major depressive disorder,4927.453903
32031,Wyoming,Male,80 to 84,Depressive disorders,2558.832942
32032,Wyoming,Male,45 to 49,Depressive disorders,4950.802837
32033,Wyoming,Female,45 to 49,Depressive disorders,8729.061004
32034,Wyoming,Male,50 to 54,Depressive disorders,4231.872417
32035,Wyoming,Female,50 to 54,Depressive disorders,7634.513551
32036,Wyoming,Male,55 to 59,Depressive disorders,3504.880493
32037,Wyoming,Female,55 to 59,Depressive disorders,6520.541177
32038,Wyoming,Male,60 to 64,Depressive disorders,3026.442439
32039,Wyoming,Female,80 to 84,Depressive disorders,3215.668210
32040,Wyoming,Female,60 to 64,Depressive disorders,5569.538243
32041,Wyoming,Female,65 to 69,Depressive disorders,4786.826997
32042,Wyoming,Male,70 to 74,Depressive disorders,2571.455510
32043,Wyoming,Female,70 to 74,Depressive disorders,3994.332305
32044,Wyoming,Male,75 to 79,Depressive disorders,2342.286437
32045,Wyoming,Female,75 to 79,Depressive disorders,3192.245853
32046,Wyoming,Male,80 plus,Depressive disorders,3001.329572
32047,Wyoming,Female,80 plus,Depressive disorders,3872.070667
32048,Wyoming,Male,65 to 69,Depressive disorders,2799.590081

### Create new data with select columns

In [19]:
new_depression_data_df = mdd.groupby(["location_name"])["val"].sum()
pd.options.display.float_format = '{:,.2f}'.format
depression_analysis = pd.DataFrame(new_depression_data_df)
depression_analysis

                            val
location_name
Alabama              285,260.92
Alaska               306,732.42
Arizona              320,307.30
Arkansas             334,072.65
California           257,912.41
Colorado             315,464.74
Connecticut          247,764.57
Delaware             289,044.07
District of Columbia 236,904.01
Florida              280,887.82
Georgia              276,781.57
Hawaii               283,780.97
Idaho                328,138.27
Illinois             245,366.87
Indiana              315,086.10
Iowa                 276,576.17
Kansas               291,509.65
Kentucky             314,783.72
Louisiana            273,734.40
Maine                300,966.97
Maryland             282,735.92
Massachusetts        264,914.13
Michigan             288,276.18
Minnesota            273,096.04
Mississippi          287,776.11
Missouri             307,588.38
Montana              330,867.74
Nebraska             267,908.98
Nevada               322,149.24
New Hampshire        301,625.78
New Jersey           230,279.30
New Mexico           337,430.79
New York             285,357.83
North Carolina       273,548.62
North Dakota         255,197.89
Ohio                 291,595.30
Oklahoma             328,486.28
Oregon               309,874.96
Pennsylvania         276,566.51
Rhode Island         306,111.61
South Carolina       293,906.12
South Dakota         247,267.87
Tennessee            316,290.77
Texas                263,132.29
Utah                 370,059.35
Vermont              300,156.53
Virginia             283,424.94
Washington           308,070.00
West Virginia        335,908.31
Wisconsin            289,377.50
Wyoming              328,378.93

### Store JSON data into a DataFrame

### Clean DataFrame

In [ ]:
new_customer_location_df = customer_location_df[["id", "address", "us_state"]].copy()
new_customer_location_df.head()

### Connect to local database

In [ ]:
rds_connection_string = "<insert user name>:<insert password>@localhost:5432/customer_db"
engine = create_engine(f'sql://{rds_connection_string}')

### Check for tables

In [ ]:
engine.table_names()

### Use pandas to load csv converted DataFrame into database

In [ ]:
new_customer_data_df.to_sql(name='customer_name', con=engine, if_exists='append', index=False)

### Use pandas to load json converted DataFrame into database

In [ ]:
new_customer_location_df.to_sql(name='customer_location', con=engine, if_exists='append', index=False)

### Confirm data has been added by querying the customer_name table
* NOTE: can also check using pgAdmin

In [ ]:
pd.read_sql_query('select * from customer_name', con=engine).head()

### Confirm data has been added by querying the customer_location table

In [ ]:
pd.read_sql_query('select * from customer_location', con=engine).head()